version: 2
jobs:
  build:
    trigger_tag:
      tag: /.*/
    working_directory: /go/src/github.com/monax/hoard
    docker:
      - image: quay.io/monax/hoard:build
    steps:
      - checkout
      - run: make build_ci
      - setup_remote_docker:
          version: 17.06.1-ce
      - run: make release

workflows:
  version: 2
  build:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+$/
